name: Anytime
version: 1.0.0
author: Lawrence Murray
email: lawrence.murray@it.uu.se
website-url: http://www.github.com/lawmurray/Anytime
download-url: http://www.github.com/lawmurray/Anytime/archive/stable.tar.gz
github-url: http://www.github.com/lawmurray/Anytime
description: "Experiments for the paper L.M. Murray, S. Singh, P.E. Jacob \& A. Lee (2016) *Anytime Monte Carlo*."
