name: Lorenz96
version: 1.0.0
author: Lawrence Murray
email: lawrence.murray@csiro.au
website-url: http://www.github.com/lawmurray/Lorenz96
download-url: http://www.github.com/lawmurray/Lorenz96/archive/master.tar.gz
github-url: http://www.github.com/lawmurray/Lorenz96
description: Lorenz '96 differential equation model.
